[package]
name = "niri"
version = "0.1.0"
description = "A scrollable-tiling Wayland compositor"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75" }
bitflags = "2.4.0"
clap = { version = "4.4.2", features = ["derive"] }
directories = "5.0.1"
image = { version = "0.24.7", default-features = false, features = ["png"] }
keyframe = { version = "1.1.1", default-features = false }
knuffel = "3.2.0"
logind-zbus = "3.1.2"
miette = { version = "5.10.0", features = ["fancy"] }
pipewire = "0.7.2"
portable-atomic = { version = "1.4.3", default-features = false, features = ["float"] }
profiling = "1.0.10"
sd-notify = "0.4.1"
serde = { version = "1.0.188", features = ["derive"] }
time = { version = "0.3.28", features = ["formatting", "local-offset", "macros"] }
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_debug"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracy-client = { version = "0.15", default-features = false }
xcursor = "0.3.4"
zbus = { version = "3.14.1" }
async-io = "1.13.0"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
# path = "../smithay"
default-features = false
features = [
    "backend_drm",
    "backend_egl",
    "backend_gbm",
    "backend_libinput",
    "backend_session_libseat",
    "backend_udev",
    "backend_winit",
    "desktop",
    "libinput_1_19",
    "renderer_gl",
    "renderer_multi",
    "use_system_lib",
    "wayland_frontend",
]

[dependencies.smithay-drm-extras]
git = "https://github.com/Smithay/smithay.git"
# path = "../smithay/smithay-drm-extras"

[features]
profile-with-tracy = ["profiling/profile-with-tracy", "tracy-client/default"]

[profile.release]
overflow-checks = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/niri", dest = "/usr/bin/", mode = "755" },
    { source = "resources/niri-session", dest = "/usr/bin/", mode = "755" },
    { source = "resources/niri.desktop", dest = "/usr/share/wayland-sessions/", mode = "644" },
    { source = "resources/niri.service", dest = "/usr/lib/systemd/user/", mode = "644" },
]
[package.metadata.generate-rpm.requires]
alacritty = "*"
